### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by weide86** [kawaapp/wsq-xiaochengxu#2]
你那个后台项目，有个文件找不到
import (
"github.com/labstack/echo"
"github.com/kawaapp/wsq/spamcheck"
)

用到的github.com/kawaapp/wsq/spamcheck，找不到，项目没法运行，请问怎么处理？，谢谢

**Comment by ntop001** [comment]
@weide86 我们后台代码是闭源的，你怎么能拿到我们的后台代码呢？(ΩДΩ)
